---
title: "Week 1 Reflections"
description: "Building my development board and programming in SystemVerilog"
author: "Rebecca Kong"
date: "9/8/26"
categories:
  - reflection
  - labreport
draft: false
---

## Summary
In this lab we assembled a development board as well as tested out the MCU and FPGA boards. However, the main focus of the lab was to program the FPGA using SystemVerilog. We wrote SystemVerilog code to control the switches, LEDs, and 7-segment display to ensure the board was operational. The programs used were Lattice Radiant (which included QuestaSim) for FPGA as well as a little bit of SEGGER Embedded Studio when testing the MCU. The lab was a succes and we were able to successfully program the FPGA to meet the specifications.

## Reflections on Lab
This lab was a great introduction to the course and it was a beneficial experience to learn how to assemble the development board--specifically learning how to solder SMT components and learning how to use solder paste. The tutorials were very beneficial in terms of refreshing my memory on topics as well as teaching me how to use new software. Personally, I found the videos most helpful as following along made the process easier.One downside was that following the instructions while clicking through all the different links and tutorials was a bit confusing. I think it would be beneficial to create an organized list of all the links and tutorials that are needed on a side bar to make locating the resources easier. There were some issues with the connecting the board to program as well as with the software programs themselves, but overall I thought the lab was very detailed and informative. I think in the future I need to first comprehensively read over the lab to try and understand the goals at hand and create a plan of action before diving into the lab. I think this will help me to be more efficient and organized in my work. Due to learning to use new tools, board soldering, and refreshing old topics, this lab took longer taking me around 30 hours.